### ISSUE TITLE
amr音频转MP3无法实现

### ISSUE THREAD

**Issue by hnzxb** [upyun/node-sdk#14]
如题，代码  
 var options = {"type": "audio", "avopts": "/f/mp3", "return_info": true, "save_as": "/test.mp3"}
                upyun.putFile(‘/test.amr’,filebuffer, 'amr', false, options, function (err, result) {
                    console.log(result);
                });

结果：amr存储成功,转码不成功

**Comment by Mohanson** [comment]
能提供你的 amr 文件吗?

**Comment by sabakugaara** [comment]
目前 node-sdk 不支持上传文件时，进行异步云处理操作

需要增加该特性

**Comment by sabakugaara** [comment]
@hnzxb use `formPutFile` method:

```
var options = {
  'content-type': 'audio/amr',
  'save-key': '/save/path.amr',
  'apps': [{
       name: "naga",
       type: "video",
       avopts:  '/f/mp3',
       return_info: true,
       save_as: '/save/path.mp3',
   }],
 };
 upyun.formPutFile('/local/path.amr', options, null, function(err, result) {
 });
```
