### ISSUE TITLE
遍历所有文件

### ISSUE THREAD

**Issue by wyl4321** [upyun/node-sdk#15]
你好，我们有多层目录，如何使用listDir借口，输入第一层目录，自动遍历所有文件，我们遍历时会提示too many requests

**Comment by kaidiren** [comment]
请问具体的使用场景是什么？是需要批量下载还是批量删除么? 现在api 层面有请求次数保护。没法规避。如果要批量删除和现在，可以使用ftp的方式。或者 https://github.com/polym/upx 。

**Comment by wyl4321** [comment]
比如我们的目录结构是2016/11/18/xxxx/xxx.jpg要遍历某天的所有文件，而xxxx目录个数比较多递归调用就会出错

**Comment by kaidiren** [comment]
@yejingx  这个目前有其他好的方法么？

**Comment by yejingx** [comment]
目前只能控制下请求频率，没有好的办法。

**Comment by kaidiren** [comment]
@wyl4321 抱歉呢。具体内容已经在上面了。现在还没有太好的办法。
