### ISSUE TITLE
缓存刷新

### ISSUE THREAD

**Issue by zhujun24** [upyun/node-sdk#18]
我在这个 SDK 里没有找到缓存刷新的功能，这个 SDK 支持 [缓存刷新](http://docs.upyun.com/api/purge/) 的功能么？如果没有的话将来会有么？

**Comment by sabakugaara** [comment]
OK 会追加下

**Comment by zhujun24** [comment]
先谢过

**Comment by sabakugaara** [comment]
@zhujun24 缓存刷新将会在第三版 sdk 添加 https://github.com/upyun/node-sdk/pull/19

**Comment by zhujun24** [comment]
我看版本已经到了3.2.6，大概什么时候出缓存刷新呢

**Comment by sabakugaara** [comment]
有了 [purge](https://github.com/upyun/node-sdk/blob/master/upyun/upyun.js#L357)

**Comment by zhujun24** [comment]
可能是初始化client时参数设置的不对，服务名指的的啥
```
{
    msg: 'bucket not exist',
    code: 40100012,
    id: 'ac3c9607df5b80455cda989b773964d1' 
}
```

**Comment by sabakugaara** [comment]
服务名指的是又拍云的空间名。原先叫**空间**，现在统一改成**服务**了

**Comment by zhujun24** [comment]
新增了操作员，然后报错 user not exists

**Comment by zhujun24** [comment]
继续报错 user not exists，操作员是不是需要这个空间的授权？

**Comment by sabakugaara** [comment]
是的，需要授权

**Comment by zhujun24** [comment]
操作员管理 https://console.upyun.com/account/operators/ 没有找到授权操作，提了工单，您知道怎么给操作员授权吗？

**Comment by sabakugaara** [comment]
这个列表里有一列“授权” ，点击“管理”，然后输入服务名就可以~

**Comment by zhujun24** [comment]
![2f9ddb25-8846-42cd-b943-046eef48a630](https://user-images.githubusercontent.com/7301773/30464009-a49bc452-9994-11e7-87ae-fcd961cc3671.png)
没找到 授权 这一列

**Comment by zhujun24** [comment]
提个建议，接口返回的错误信息详细一些，这样对调试更友好一些，要不然得去源码里面 debug

**Comment by sabakugaara** [comment]
好的，感谢建议
