### ISSUE TITLE
我按照readme的方法，总是报如下错误

### ISSUE THREAD

**Issue by xygahs0801** [upyun/node-sdk#22]
![image](https://user-images.githubusercontent.com/3293775/27020323-9bed3b18-4f72-11e7-8f0d-bc4daeb936f4.png)

**Comment by sabakugaara** [comment]
`User-Agent` 的确不允许在客户端使用，下个版本修复下。
不过应该不会影响实际使用，可否将未捕获的 promise 错误，捕获下？提供更具体的错误信息

**Comment by sabakugaara** [comment]
@xygahs0801 已经修复发布 感谢反馈~
