### ISSUE TITLE
formPutFile 返回值问题

### ISSUE THREAD

**Issue by cherry-geqi** [upyun/node-sdk#24]
`formPutFile` 只返回 `true` 或 `false`，对于将 `save-key` 设置为 `/{random32}{.suffix}/` 的请求，上传成功后，根本拿不到文件名。

**Comment by sabakugaara** [comment]
好的，我发个版本调整下

**Comment by sabakugaara** [comment]
3.1.0 版本 @cherry-geqi 感谢反馈~
