### ISSUE TITLE
42900002 too many requests of the same uri

### ISSUE THREAD

**Issue by tenjj** [upyun/node-sdk#27]
我这边图片上传已经使用 async eachLimit 进行了并发限制为2  为何有时候还是会报这个错误

eachLimit(imgbox, 2, (img, cb) => {
  upyun.putFile(xx, xx)
    .then(res => {
      log(`上传成功: xx`)
      cb()
    })
    .catch(err => {
      reject(`上传失败: xx`)
      cb()
    })
})

**Comment by sabakugaara** [comment]
@tenjj 这个限制是又拍云服务端做的。你是不是总量比较多，做的批量上传？

短时间大量上传的话，服务端就会报这个错误
