### ISSUE TITLE
当 statusCode 不为 200 时，promise 回调不执行

### ISSUE THREAD

**Issue by cherry-geqi** [upyun/node-sdk#30]
https://github.com/upyun/node-sdk/blob/184812cebdc9d0072492ce4037122e0a7e7f5dbf/upyun/form-upload.js#L14-L16

当 statusCode 不为 200 时，promise 既不 resolve() 也不 reject()，导致 then() 和 catch() 的回调永不执行。

**Comment by sabakugaara** [comment]
感谢，已经发布新版本 3.2.4
