### ISSUE TITLE
如何实现通过 Proxy 的调用

### ISSUE THREAD

**Issue by syhily** [upyun/node-sdk#33]
你好，我工作的公司上网环境是需要通过代理的，无法直接访问UPYUN，请问如何在此SDK上实现呢？

**Comment by sabakugaara** [comment]
不是很清楚你的上网环境，如果你们是全部网络走公司的代理出口，要确认下代理或者防火墙之类的是不是
允许访问又拍云 v0.api.upyun.com 的请求。

**Comment by sabakugaara** [comment]
@syhily 如果有问题再打开
