### ISSUE TITLE
报错啊大兄弟

### ISSUE THREAD

**Issue by delayhsiao** [upyun/node-sdk#38]
create-req.js?f663:27 Uncaught (in promise) TypeError: Cannot read property 'then' of undefined
    at __webpack_exports__.a.req.interceptors.request.use (create-req.js?f663:27)
![image](https://user-images.githubusercontent.com/9155059/38666203-f770d9f2-3e70-11e8-8f40-fcdb76c0fb4b.png)

**Comment by sabakugaara** [comment]
`getHeaderSign` 必须返回一个 promise
