### ISSUE TITLE
接入很顺利，但有几个小建议

### ISSUE THREAD

**Issue by Lanfei** [upyun/node-sdk#4]
1. `policy ` 和 `signature` 的生成能否直接封装成方法呢？
2. 当 `return-url` 不以 `http` 或 `https` 开头的时候，能否通过请求的 `Origin` 头或 `Referer` 头来拼接？

场景如下：
通常我们的项目都会部署在多个环境，比如本地开发环境，测试环境，预发布环境，生产环境等等，而这些环境的域名也不一样，那么我在生成 `policy` 的时候，就得对应不同的环境去配置不同的 `return-url` ，这个虽然不难，但实在不够优雅，所以如果可以直接这样配置：

```js
{
	'bucket': bucket,
	'save-key': filename,
	'return-url': '/api/files/callback',
	'expiration': Math.round(Date.now() / 1000) + 3600
}
```

就可以适用所有场景的话，就最好了。

**Comment by kaidiren** [comment]
感谢建议。

第一条当然是可以的。稍后会更新在随后的版本里。

第二条，我们这边讨论下实时的可行性和方案。实施可行性或者如何实时，后续会给出回复。

欢迎关注~  😄

**Comment by Lanfei** [comment]
(ヾﾉ･ω･`)嗨，讨论结果如何？

**Comment by kaidiren** [comment]
小工具什么的，写好了，在处理文档。

**Comment by kaidiren** [comment]
当 return-url 不以 http 或 https 开头的时候，能否通过请求的 Origin 头或 Referer 头来拼接？
场景如下：
通常我们的项目都会部署在多个环境，比如本地开发环境，测试环境，预发布环境，生产环境等等，而这些环境的域名也不一样，那么我在生成 policy 的时候，就得对应不同的环境去配置不同的 return-url ，这个虽然不难，但实在不够优雅，所以如果可以直接这样配置：

这一条的话我自己也尝试了一下。

**Comment by kaidiren** [comment]
除非是跟前端关联起来，前段页面可能会把Origin 头或 Referer 头 附带在请求里，如果只是后端上传的话，如果采用这样的方式还是需要自己拼接上 这些头信息的，如果一旦这么做，反而又不方便了。

**Comment by kaidiren** [comment]
通常我们的项目都会部署在多个环境，比如本地开发环境，测试环境，预发布环境，生产环境等等，

根据不同的环境配置不同的变量，目前来说是一种比较合理的方式。虽然这么做会有点麻烦，其实就是为了控制风险。如果sdk帮忙做了补全的事情，线上的时候由于某种情况头信息不在了。debug起来会非常头疼的。所以为了安全也确实是可以适当繁琐一点的。

**Comment by kaidiren** [comment]
非常感觉您的关注。我会尽快把文档补全放上去的。争取明天就放上去。😄 

拖的有点久了，抱歉。感谢督促。

**Comment by kaidiren** [comment]
https://github.com/upyun/node-sdk#tools

**Comment by Lanfei** [comment]
收到，下午试试~
