### ISSUE TITLE
从服务器端获取签名后,发起上传文件请求, 浏览器收到报错Request header field 0 is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by MusaZhou** [upyun/node-sdk#44]
发起上传文件请求后, 似乎js sdk先发起了一个method 为OPTIONS的请求, 收到响应后第二个请求报错
Request header field 0 is not allowed by Access-Control-Allow-Headers in preflight response.
这是chrome上的截图
![image](https://user-images.githubusercontent.com/5696343/46055235-91716280-c17d-11e8-863a-4030981fb096.png)
这个回复是因为什么造成的呢?是签名不正确吗?谢谢

**Comment by kaidiren** [comment]
请参考 https://github.com/upyun/node-sdk/tree/master/sample

**Comment by MusaZhou** [comment]
恩,我是参照这个例子写的, 可是我的后台是python,现在返回401, 应该是那边的签名函数有问题.
