### ISSUE TITLE
nodejs端上传string显示401

### ISSUE THREAD

**Issue by liu2080019** [upyun/node-sdk#51]
`const BUCKET = '服务名';`
`const BUCKET_URL_ROOT = '域名'`;
`const FROM_API_SECRET = '密码'`;
`const ADMIN_USERNAME = '账号';`
`const upService = new upyun.Service(BUCKET, ADMIN_USERNAME, FROM_API_SECRET);`
`const upClient = new upyun.Client(upService);`
`const params = { 'notify-url':  BUCKET_URL_ROOT };`
`const fileName = "文件名.html";`
`const fileString = "一段html字符串"`;
`upClient.putFile(fileName, fileString, params).then(res => {`
    `console.log(res);`
`}).catch(err => {`
    ` console.log(err)`
`})`

错误是`upyun - response error: Request failed with status code 401`

 有点懵逼 ， 我是在nodejs端直接调用的，fileString是字符串，因为我看你们的文档是支持直接字符串上传的，求解

**Comment by kaidiren** [comment]
https://github.com/upyun/node-sdk/blob/master/examples/process.js

请参照这里或者测试用例里的代码
https://github.com/upyun/node-sdk/blob/master/tests/server/upyun.js

**Comment by liu2080019** [comment]
> https://github.com/upyun/node-sdk/blob/master/examples/process.js
> 
> 请参照这里或者测试用例里的代码
> https://github.com/upyun/node-sdk/blob/master/tests/server/upyun.js

示例代码没问题。  我这边账号密码的问题。 已解决
