### ISSUE TITLE
putFile options Content-MD5 返回401

### ISSUE THREAD

**Issue by abcdGJJ** [upyun/node-sdk#53]
```
const md5 = require('md5');
fs.readFile(filepath, async (err, data) => {
  if (err) throw err;
  // 计算文件md5，并存储到upyun
  await this.client.putFile(`/test/c/index2.html`, data, {
     'Content-MD5': md5(data)
   });
});
```
账号密码没有问题  不加options也没有问题  一加上options就返回401

**Comment by zyvas** [comment]
@abcdGJJ 已支持. 使用示例见测试 https://github.com/upyun/node-sdk/blob/master/tests/server/upyun.js#L39

**Comment by abcdGJJ** [comment]
@zyvas   功能和我想的不一样啊 ，我以为加个Content-MD5然后headFile的时候就有md5值了，结果只是上传时校验md5值一直不一致

**Comment by zyvas** [comment]
> @zyvas 功能和我想的不一样啊 ，我以为加个Content-MD5然后headFile的时候就有md5值了，结果只是上传时校验md5值一直不一致

没有理解这句话的意思. 上传时报错了么 ?

**Comment by abcdGJJ** [comment]
没报错  但不是我理解的那种功能  headFile返回值里的Content-Md5不是可能不存在么  我理解的是只有putFile 参数里加上md5然后在请求文件信息的时候才会返  现在发现并不是

**Comment by weijiatan456** [comment]
`const md5 = require('md5');
const service = new upyun.Service(serviceName, operatorName, operatorPassword);
const client = new upyun.Client(service);
const stream = await ctx.getFileStream();
let options = {
    'Content-Md5':md5(stream)
}
const res = await client.putFile(remotePath,stream,options)`

同问：账号密码没有问题，不加options也没有问题，一加上options就报错

**Comment by 743v45** [comment]
@weijiatan456 https://www.npmjs.com/package/md5#api
md5 没有支持 stream 计算，确定一下 content-md5 为实际内容计算结果

https://github.com/upyun/node-sdk/blob/master/tests/server/upyun.js#L47
测试用例使用的是直接获取内容（当然，该方法不适合大文件读取）

**Comment by weijiatan456** [comment]
> @weijiatan456 https://www.npmjs.com/package/md5#api
> md5 没有支持 stream 计算，确定一下 content-md5 为实际内容计算结果
> 
> https://github.com/upyun/node-sdk/blob/master/tests/server/upyun.js#L47
> 测试用例使用的是直接获取内容（当然，该方法不适合大文件读取）


感谢，我通过File模式上传，ctx.request.files获取文件信息，成功了！
使用Stream模式，还真无法md5校验！
