### ISSUE TITLE
upyun.common 构建错误

### ISSUE THREAD

**Issue by Senasiko** [upyun/node-sdk#69]
在 `upyun.common.js` 中 fs 模块的处理出现了错误。
https://github.com/upyun/node-sdk/blob/09b9b7270fbfa4ca591aceb1e53d69964c78ea3c/dist/upyun.common.js#L1584
`rollup-plugin-node-resolve` 的文档中有提到[解决办法](https://github.com/rollup/rollup-plugin-node-resolve#resolving-built-ins-like-fs)。

**Comment by zyvas** [comment]
已于 `v3.4.1` 合入
