### ISSUE TITLE
copy接口报错

### ISSUE THREAD

**Issue by wyshikai837** [upyun/node-sdk#72]
Uncaught (in promise) TypeError: utils.isSuccess is not a function at eval (upyun.esm.js?814b:2915)
查看代码发现**upyun.esm.js**中utils有问题，希望早日修复
upyun.esm.js中的utils如下：
```
var utils = {
  readBlockAsync: readBlockAsync
};
```
而upyun.common.js中的utils为：
```
var utils = {
  readBlockAsync: readBlockAsync,
  getFileSizeAsync: getFileSizeAsync,
  getContentType: getContentType,
  isSuccess: isSuccess
};
```
缺少了三个函数

**Comment by zyvas** [comment]
getFileSizeAsync / getContentType 未在浏览器端使用，（增加过判断）

于 0c70d0814e319b1635c499207e765cd2708c1713 引入了新方法 `isSuccess` 未对前端文件 `./upyun/browser-utils.js` 做兼容。

已经通过 https://github.com/upyun/node-sdk/commit/86fe3123bbbe6ad711466caa78f4b98b98345da9 移除，发布 `v3.4.2`
