### ISSUE TITLE
formPutFile 图片上传成功但是无法查看预览

### ISSUE THREAD

**Issue by liuyayaya** [upyun/node-sdk#74]
` let imgBuffer = new Buffer.from(imgData, 'base64')`
` let uploadData = await upyunClient.formPutFile(`/website/${file.name}`, imgBuffer, {"Content-Type": file.type});`

将浏览器端上传的base64 图片转成buffer 后上传，接口调用成功。但是图片无法预览查看
![image](https://user-images.githubusercontent.com/8876619/96210517-ac051700-0fa4-11eb-99d1-e94ba795d628.png)
![image](https://user-images.githubusercontent.com/8876619/96210694-00a89200-0fa5-11eb-84e0-a91cd081ae3b.png)

**Comment by 743v45** [comment]
@liuyayaya 
https://nodejs.org/dist/latest-v12.x/docs/api/buffer.html#buffer_static_method_buffer_from_string_encoding
`let imgBuffer = Buffer.from(imgData, 'base64')`  是由 base64 编码过的 `imgData` 转为通用 `buffer` 的 `imgBuffer`，
看起来，此处应该使用编码而不是解码

**Comment by 743v45** [comment]
无更新，先关闭该 issues

若有疑问再打开
