### ISSUE TITLE
能否提供 Buffer 或 Stream 上传的 API？

### ISSUE THREAD

**Issue by Lanfei** [upyun/node-sdk#8]
有时候需要在服务端进行上传，比如微信登录接入抓取头像等，按现有 API，只能保存到本地，再进行上传，再删除保存的临时文件，这样不但麻烦，性能也差，所以请问能否提供 Buffer 或 Stream 上传的 API？

**Comment by kaidiren** [comment]
因为签名认证是需要知道文件的大小的就是 CONTENT_LENGTH

http://docs.upyun.com/api/rest_api/#_3

用流的话其实是不知道文件大小的。即使间接的实现了，也会用起来很不方便。

所以推荐用 form  上传的方式 。

这里有个小例子：

https://github.com/upyun/node-sdk/blob/master/sample/form_upload.js

**Comment by kaidiren** [comment]
因为签名认证是需要知道文件的大小的就是 CONTENT_LENGTH

http://docs.upyun.com/api/rest_api/#_3

用流的话其实是不知道文件大小的。即使间接的实现了，也会用起来很不方便。

你的文件也不存在服务器本地也不符合 form 上传的模型。

倒是类似于一种 注入的模型。把别人的url 上的资源存放在自己的 空间里。

这个我们有个接口暂时还没有对外开放。

可以点我头像邮箱联系试用。

感谢反馈！ 😀

**Comment by Lanfei** [comment]
好的，已向你发邮件申请，望回复~
